catch_rules:
- rule: _
  transform_rules:
  - replace: ''
    search: \#.*
    searchin: url
  - action: fetch
    fetch:
      delay: 200
    search: _
  - action: redirect
    redirect:
      status: 301
      url: https://google.com
    search: \/google$
  - action: redirect
    redirect:
      status: 301
      to: /$1.html
    search: \/([^\/.]+)$
  - replace: blogcdn/redish101-blog@1.3.657896566/public
    search: ([^\/.]+)\/$
  - replace: blogcdn/redish101-blog@1.3.657979621/public
    search: _
  - action: fetch
    fetch:
      cache:
        delay: 200
        expire: 1000*60
        expired_delay: 500
      engine: parallel
      preflight: false
      status: 200
      timeout: 5000
    replace:
    - https://cdn.jsdelivr.net/npm
    - https://cdn1.tianli0.top/npm
    - https://jsd.onmicrosoft.cn/npm
    - https://unpkg.onmicrosoft.cn
    - https://unpkg.com
    - https://npm.sourcegcdn.com
    search: ^https\:\/\/blogcdn
  - header:
      ServerProvide: Redish101BlogHelper
      content-type: text/html;charset=utf-8
    search: \.html$
- rule: .*
  transform_rules:
  - action: fetch
    fetch:
      enable: true
      engine: fetch
      preflight: false
    search: .*
  - action: return
    return:
      body: "emm,\u770B\u6765101\u7684\u7A0B\u5E8F\u53C8\u6709bug\u4E86......"
      header:
        ServerProvide: Redish101BlogHelper
        content-type: text/plain;charset=utf-8
      status: 503
    search: (^4|^5)
    searchin: status
name: Redish101BlogHelper
