######## Stellar info ########
stellar:
  version: '1.9.0'
  homepage: 'https://xaoxuu.com/wiki/stellar/'
  repo: 'https://github.com/xaoxuu/hexo-theme-stellar'
  cdn_css: # Use cdn links instead of /css/main.css
  cdn_js: # Use cdn links instead of /js/main.js


######## head tags ########
open_graph:
  enable: true
  twitter_id: # for open_graph meta


######## Sidebar ########
sidebar:
  logo:
    avatar: '[config.avatar](/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
    post: '[btn.blog](/)'
    friends: '[btn.link](/links/)'
    wiki: '[btn.wiki](/wiki/)'
    talk: '[btn.talk](/talks/)'
    sub: '[订阅](/sub/)'
    # about: '[关于](/about/)'
  # Sidebar widgets
  widget_layout:
    index: [recent] # for home/wiki/categories/tags/archives/404 pages
    page: [toc] # for pages using 'layout:page'
    post: [toc, repo_info] # for pages using 'layout:post'
    wiki: [toc, repo_info, wiki_more] # for pages using 'layout:wiki'
  widgets:
    # Recent update
    recent:
      layout: recent
      rss: /atom.xml
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.
    # welcome
    welcome:
      layout: markdown
      title: Redish101的小站
      content: | # support markdown
        感谢您访问本站，本站源码在[Redish101/blog](https://github.com/Redish101/blog)



######## Main ########
breadcrumb:
  home: home # config.title / config.author / home or custom content

######## Article ########
article:
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面图片？
  auto_cover: false # search from https://source.unsplash.com/
  # 如果没有指定横幅，是否根据 tags 作为关键词搜索横幅图片？
  auto_banner: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 200
  # 分类颜色
  category_color:
  # 文章许可协议
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享
  share: [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    max_count: 5
    auto_cover: true # 如果没有封面就根据 tags 作为关键词搜索封面，开了此项将不会自动从文章中提取首张图片作为封面了。


######## Comments ########
comments:
  service: beaudar # beaudar, utterances, valine, twikoo, waline
  # beaudar
  # https://beaudar.lipk.org/
  beaudar:
    repo: Redish101/blog
    issue-term: pathname
    issue-number:
    theme: preferred-color-scheme
    label: comments
    input-position: top # top/bottom 评论框位置
    comment-order: desc # desc 排序
    keep-theme: # true/false
    loading: false
    branch: main
  # utterances
  # https://utteranc.es/
  utterances:
    repo: xxx/xxx
    issue-term: pathname
    issue-number:
    theme: preferred-color-scheme
    label:
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    data-repo: Redish101/blog # [在此输入仓库]
    data-repo-id: # [在此输入仓库 ID]
    data-category: # [在此输入分类名]
    data-category-id:
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous

  valine:
    js: https://cdn1.tianli0.top/gh/XuxuGood/simple-blog-cdn@main/js/Valine.min.js
    appId: # your appId
    appKey: # your appKey
    placeholder:
    requiredFields: [nick, mail]
    enableQQ: true # Unstable avatar link
    recordIP: false # Record commenter IP
    avatar: robohash # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    lang: zh-cn
    highlight: true
    mathJax: false
    tagMeta: [博主, 小伙伴, 访客] # 标签要显示的文字,默认'博主,小伙伴,访客'
    metaPlaceholder:
      nick: "昵称/QQ号(必填)"
      mail: "邮箱（必填，完全保密）"
      link: "网址(https://)"
    master: #md5加密后的博主邮箱
      - 6783037F2DF30EAB99F9FC256157D875
    friends: #md5加密后的小伙伴邮箱
      - 6783037F2DF30EAB99F9FC256157D875
  # Twikoo
  # https://twikoo.js.org/
  twikoo:
    js: https://cdn1.tianli0.top/npm/twikoo@1.4.0/dist/twikoo.all.min.js # 建议锁定版本
    envId: https://xxx # vercel函数
  waline:
    js: https://unpkg.com/@waline/client@v2/dist/waline.js
    css: https://unpkg.com/@waline/client@v2/dist/waline.css
    # Waline server address url, you should set this to your own link
    serverURL:

    # If false, comment count will only be displayed in post page, not in home page
    commentCount: true

    # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`.
    pageview: false

    # Custom locales
    # locale:
    #   placeholder: Welcome to comment # Comment box placeholder

    # Custom emoji
    # emoji:
    #   - https://unpkg.com/@waline/emojis@1.0.1/weibo
    #   - https://unpkg.com/@waline/emojis@1.0.1/alus
    #   - https://unpkg.com/@waline/emojis@1.0.1/bilibili
    #   - https://unpkg.com/@waline/emojis@1.0.1/qq
    #   - https://unpkg.com/@waline/emojis@1.0.1/tieba
    #   - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji

    # Comment infomation, valid meta are nick, mail and link
    # meta:
    #   - nick
    #   - mail
    #   - link

    # Set required meta field, e.g.: [nick] | [nick, mail]
    # requiredMeta:
    #   - nick

    # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    # lang: zh-CN

    # Word limit, no limit when setting to 0
    # wordLimit: 0

    # Whether enable login, can choose from 'enable', 'disable' and 'force'
    # login: enable

    # comment per page
    # pageSize: 10

######## Footer ########
footer:
  social:
    # github:
    #   icon: '<img src="https://cdn1.tianli0.top/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
    #   url: /
    # music:
    #   icon: '<img src="https://cdn1.tianli0.top/gh/cdn-x/placeholder@1.0.3/social/3845874.svg"/>'
    #   url: /
    # unsplash:
    #   icon: '<img src="https://cdn1.tianli0.top/gh/cdn-x/placeholder@1.0.3/social/3616429.svg"/>'
    #   url: /
    # comments:
    #   icon: '<img src="https://cdn1.tianli0.top/gh/cdn-x/placeholder@1.0.3/social/942ebbf1a4b91.svg"/>'
    #   url: /about/#comments
  sitemap:
    # '博客':
    #   - '[近期](/)'
    #   - '[分类](/)'
    #   - '[标签](/)'
    #   - '[归档](/)'
    # '项目':
    #   - '[开源库](/)'
    # '社交':
    #   - '[友链](/)'
    #   - '[留言板](/)'
    # '更多':
    #   - '[关于本站](/)'
    #   - '[GitHub](/)'
  more: | # 支持 Markdown 格式
    本站采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处
  content: | # 支持 Markdown 格式
    Powered by Hexo and Stellar
  # 主题用户越多，开发者维护和更新的积极性就越高，如果您喜欢本主题，请在适当的位置显示主题信息和仓库链接以表支持。


######## Tag Plugins ########
tag_plugins:
  # {% note text %}
  note:
    default_color: '' # light, dark, red, orange, yellow, green, cyan, blue, purple
  # {% checkbox %}
  checkbox:
    interactive: false # enable interactive for user
  # {% quot %}
  quot:
    default: # 可以自行配置多种图标方案
      prefix: https://s2.loli.net/2022/01/04/vsTB5pGrIHfPxSj.png
      suffix: https://s2.loli.net/2022/01/04/NORdtjlAhifZSns.png
    hashtag:
      prefix: https://s2.loli.net/2022/01/04/UvHcsa73jQPnobq.png
  # {% emoji %}
  emoji:
    default: https://cdn1.tianli0.top/gh/volantis-x/cdn-emoji/qq/%s.gif
    twemoji: https://cdn1.tianli0.top/gh/twitter/twemoji/assets/svg/%s.svg
    qq: https://cdn1.tianli0.top/gh/volantis-x/cdn-emoji/qq/%s.gif
    aru: https://cdn1.tianli0.top/gh/volantis-x/cdn-emoji/aru-l/%s.gif
    tieba: https://cdn1.tianli0.top/gh/volantis-x/cdn-emoji/tieba/%s.png
  # {% image %}
  image:
    fancybox: # true, false


######## JS Plugins ########
plugins:
  ## required plugins ##
  # jquery
  jquery: https://cdn1.tianli0.top/npm/jquery@3.5.1/dist/jquery.min.js

  # issues api
  sitesjs: /js/plugins/sites.js
  friendsjs: /js/plugins/friends.js

  ## optional plugins ##
  # preload
  preload:
    enable: true
    service: flying_pages # instant_page, flying_pages
    instant_page: https://cdn1.tianli0.top/gh/volantis-x/cdn-volantis@4.1.2/js/instant_page.js
    flying_pages: https://cdn1.tianli0.top/gh/gijo-varghese/flying-pages@2.1.2/flying-pages.min.js

  # image lazyload
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true # [hexo clean && hexo s] is required after changing this value.
    js: https://cdn1.tianli0.top/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
    transition: blur # blur, fade

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    enable: #true
    js: https://cdn1.tianli0.top/npm/scrollreveal@4.0.9/dist/scrollreveal.min.js
    distance: 8px
    duration: 500 # ms
    interval: 100 # ms
    scale: 1 # 0.1~1

  # https://fancyapps.com/docs/ui/fancybox/
  # available for {% image xxx %}
  fancybox:
    enable: true
    js: https://cdn1.tianli0.top/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js
    css: https://cdn1.tianli0.top/npm/@fancyapps/ui@4.0/dist/fancybox.css
    # 可以处理评论区的图片（不支持 iframe 类评论系统）例如：
    # 使用valine评论可以写: .vcontent img:not(.vemoji)
    # 使用twikoo评论可以写: .tk-content img:not([class*="emo"])
    # 使用waline评论可以写: #waline_container .vcontent img
    selector: .swiper-slide img # 多个选择器用英文逗号隔开

  # swiper
  swiper:
    enable: true
    css: https://unpkg.com/swiper@6/swiper-bundle.min.css
    js: https://unpkg.com/swiper@6/swiper-bundle.min.js


  # 赫蹏 (Heti) - 专为中文网页内容设计的排版样式增强
  # https://github.com/sivan/heti
  heti:
    enable: false
    css: https://unpkg.com/heti/umd/heti.min.css
    js: https://unpkg.com/heti/umd/heti-addon.min.js

  # MathJax
  # 需在Markdown文件开头加入mathjax: true
  # 推荐使用Pandoc: npm uninstall hexo-renderer-marked --save & npm install hexo-renderer-pandoc --save
  mathjax:
    enable: false
    cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML

  # Katex - The fastest math typesetting library for the web
  # https://katex.org/docs/autorender.html
  # https://github.com/KaTeX/KaTeX
  # 使用 hexo-renderer-markdown-it-plus 作为公式渲染器：npm uninstall hexo-renderer-marked --save npm install hexo-renderer-markdown-it-plus --save
  katex:
    enable: false
    min_css: <link rel="stylesheet" href="https://cdn1.tianli0.top/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    min_js: <script defer src="https://cdn1.tianli0.top/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    auto_render_min_js: <script defer src="https://cdn1.tianli0.top/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"onload="renderMathInElement(document.body);"></script>

style:
  darkmode: auto # auto / always / false
  smooth_scroll: true # true / false
  theme:
    light: '#f8f8f8'
    dark: '#313438'
  animated_avatar:
    animate: auto # auto, always
    background: https://cdn1.tianli0.top/gh/cdn-x/placeholder@1.0.2/avatar/round/rainbow64@3x.webp
  codeblock:
    scrollbar: 4px
    highlightjs_theme: https://cdn1.tianli0.top/gh/highlightjs/cdn-release@11.5.0/build/styles/atom-one-dark.min.css

default:
  avatar: https://cdn1.tianli0.top/gh/cdn-x/placeholder@1.0.1/avatar/round/3442075.svg
  link: https://cdn1.tianli0.top/gh/cdn-x/placeholder@1.0.1/link/8f277b4ee0ecd.svg
  cover: https://cdn1.tianli0.top/gh/cdn-x/placeholder@1.0.1/cover/76b86c0226ffd.svg
  image: https://cdn1.tianli0.top/gh/cdn-x/placeholder@1.0.1/image/2659360.svg
